<a href="https://colab.research.google.com/github/FlorentGerbaud/Deep-Learning/blob/main/%5BTD1%5D%20-%20Introduction%20to%20Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Lab 1: Torch basics
# The goal of this lab is to discover Pytorch, especially the Tensor concept.


In [4]:
torch.__version__

'2.4.1+cu121'

In [3]:
import matplotlib.pyplot as plt
%matplotlib inline
import torch
import numpy as np

Largely inspired from the tutorial [What is PyTorch?](https://pytorch.org/tutorials/beginner/former_torchies/tensor_tutorial.html)

Tensors are used to encode the signal to process, but also the internal states and parameters of models.

Manipulating data through this constrained structure allows to use CPUs and GPUs at peak performance.



## Tensors

Construct a 3x5 matrix, uninitialized:

In [5]:
# Set the default floating point dtype to float32
torch.set_default_dtype(torch.float32)

# Optional: Set the default device to 'cuda' if available, otherwise 'cpu'
device = 'cuda' if torch.cuda.is_available() else 'cpu'
torch.set_default_device(device)
print(device)

cuda


In [6]:
x = torch.empty(3,5)
print(x.type())
print(x)

torch.cuda.FloatTensor
tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]], device='cuda:0')


In [7]:
x = torch.randn(3,5)
print(x)

tensor([[-1.6264, -2.0400,  0.9369,  1.0051, -1.0654],
        [ 0.0082, -0.3993,  0.7165,  1.0749,  0.1928],
        [-2.0833, -0.2793, -0.1986, -0.1956, -0.2467]], device='cuda:0')


In [ ]:
print(x.size())

torch.Size([3, 5])


torch.Size is in fact a [tuple](https://docs.python.org/3/tutorial/datastructures.html#tuples-and-sequences), so it supports the same operations.

In [ ]:
x.size()[1]

5

In [ ]:
x.size() == (3,5)

True

Importance of the brackets when defining a tensor

In [ ]:
a = torch.tensor([2.0])
print(type(a))
print(a.dtype)
print(a.size())

b = torch.tensor(2.0)
print(type(b))
print(b.dtype)
print(b.size())

<class 'torch.Tensor'>
torch.float32
torch.Size([1])
<class 'torch.Tensor'>
torch.float32
torch.Size([])


Select some columns

In [ ]:
cols = torch.zeros(5, dtype=torch.bool)
print(cols)
cols[1] = True
cols[4] = True
print(cols)
c = x[:, cols]  # selects all rows, 2nd column and  5th column from x
print(c)

tensor([False, False, False, False, False])
tensor([False,  True, False, False,  True])
tensor([[-1.0853,  0.7575],
        [ 0.8747, -1.3225],
        [-1.8220, -0.5641]])


All operations on the tensor that operate in-place on it will have an _ postfix.

In [ ]:
# x will be filled with the value 3.5
x.fill_(3.5)
print(x)

tensor([[3.5000, 3.5000, 3.5000, 3.5000, 3.5000],
        [3.5000, 3.5000, 3.5000, 3.5000, 3.5000],
        [3.5000, 3.5000, 3.5000, 3.5000, 3.5000]])


## Bridge to numpy

In [ ]:
y = x.numpy()
print(y)

[[3.5 3.5 3.5 3.5 3.5]
 [3.5 3.5 3.5 3.5 3.5]
 [3.5 3.5 3.5 3.5 3.5]]


In [ ]:
a = np.ones(5)
b = torch.from_numpy(a)
print(b)


tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [ ]:
xr = torch.randn(3, 5)
a = np.ones(5).astype(int)
b = torch.from_numpy(a)
print(xr)
print(b)

tensor([[ 0.3932,  0.9812,  0.3740,  0.5793,  1.1193],
        [-0.1201, -1.2035, -1.5816,  0.1446, -1.1582],
        [-0.4286, -0.6194, -0.0633, -0.9866, -0.5791]])
tensor([1, 1, 1, 1, 1])


### Question: print the type of the content (data) of variables a, b and xr

In [ ]:
# Code here
print(a.dtype)
print(b.dtype)
print(xr.dtype)

int64
torch.int64
torch.float32


## Operations

There are multiple syntaxes for operations. In the following
example, we will take a look at the addition operation.

Addition: syntax 1

In [ ]:
x = torch.rand(5, 3)
y = torch.rand(5, 3)
print(x + y)

tensor([[0.7365, 0.6460, 1.3457],
        [1.3899, 1.3720, 1.2398],
        [1.2975, 0.9966, 1.0510],
        [0.3478, 0.7811, 1.1002],
        [0.9447, 1.2892, 0.9069]])


Addition: syntax 2

In [ ]:
print(torch.add(x, y))

tensor([[0.7365, 0.6460, 1.3457],
        [1.3899, 1.3720, 1.2398],
        [1.2975, 0.9966, 1.0510],
        [0.3478, 0.7811, 1.1002],
        [0.9447, 1.2892, 0.9069]])


Addition: providing an output tensor as argument

In [ ]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[0.7365, 0.6460, 1.3457],
        [1.3899, 1.3720, 1.2398],
        [1.2975, 0.9966, 1.0510],
        [0.3478, 0.7811, 1.1002],
        [0.9447, 1.2892, 0.9069]])


Addition: in-place

In [ ]:
# adds x to y
y.add_(x)
print(y)

tensor([[0.7365, 0.6460, 1.3457],
        [1.3899, 1.3720, 1.2398],
        [1.2975, 0.9966, 1.0510],
        [0.3478, 0.7811, 1.1002],
        [0.9447, 1.2892, 0.9069]])


**Note:** Any operation that mutates a tensor in-place is post-fixed with an ``_``.
    For example: ``x.copy_(y)``, ``x.t_()``, will change ``x``.



Any operation that mutates a tensor in-place is post-fixed with an ```_```

For example: ```x.copy_(y)```, ```x.t_()```, will change ```x```.

In [ ]:
print(x.t())

tensor([[0.7008, 0.8167, 0.4741, 0.0446, 0.6997],
        [0.4024, 0.8321, 0.5033, 0.0141, 0.6986],
        [0.5622, 0.6751, 0.7587, 0.7399, 0.4198]])


In [ ]:
print(x)

tensor([[0.7008, 0.4024, 0.5622],
        [0.8167, 0.8321, 0.6751],
        [0.4741, 0.5033, 0.7587],
        [0.0446, 0.0141, 0.7399],
        [0.6997, 0.6986, 0.4198]])


In [ ]:
x.t_()
print(x)

tensor([[0.7008, 0.8167, 0.4741, 0.0446, 0.6997],
        [0.4024, 0.8321, 0.5033, 0.0141, 0.6986],
        [0.5622, 0.6751, 0.7587, 0.7399, 0.4198]])


You can use standard NumPy-like indexing with all bells and whistles!

In [ ]:
print(x[:, 1])

tensor([0.8167, 0.8321, 0.6751])


Resizing (very useful): If you want to resize/reshape tensor, you can use ``torch.view``:

In [ ]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


If you have a one element tensor, use ``.item()`` to get the value as a
Python number

In [ ]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([1.0008])
1.0007741451263428


**Read later:**


  100+ Tensor operations, including transposing, indexing, slicing,
  mathematical operations, linear algebra, random numbers, etc.,
  are described
  [here](https://pytorch.org/docs/torch).

## 3D Tensors

### Question: What is the size of the following tensor?

In [ ]:
y = torch.tensor([
     [
       [1, 2, 3],
       [4, 5, 6]
     ],
     [
       [1, 2, 3],
       [4, 5, 6]
     ],
     [
       [1, 2, 3],
       [4, 5, 6]
     ]
   ])
print(y)

tensor([[[1, 2, 3],
         [4, 5, 6]],

        [[1, 2, 3],
         [4, 5, 6]],

        [[1, 2, 3],
         [4, 5, 6]]])


In [ ]:
# Code here

### Question: Explain the result of the next cell

In [ ]:
torch.sum(y, dim=0)

tensor([[ 3,  6,  9],
        [12, 15, 18]])

## Broadcasting semantics

In short, if a PyTorch operation supports broadcast, then its Tensor arguments can be automatically expanded to be of equal sizes (without making copies of the data).

Two tensors are “broadcastable” if the following rules hold:

*   Each tensor has at least one dimension.
*   When iterating over the dimension sizes, **starting at the trailing dimension**, the dimension sizes must either be equal, one of them is 1, or one of them does not exist.

If two tensors x, y are “broadcastable”, the resulting tensor size is calculated as follows:
* If the number of dimensions of x and y are not equal, prepend 1 to the dimensions of the tensor with fewer dimensions to make them equal length.
* Then, for each dimension size, the resulting dimension size is the max of the sizes of x and y along that dimension.

More details [here](https://pytorch.org/docs/stable/notes/broadcasting.html)



In [ ]:
# can line up trailing dimensions to make reading easier
x=torch.empty(5,1,4,1)
y=torch.empty(  3,1,1)
print((x+y).size())


torch.Size([5, 3, 4, 1])


In [ ]:
# but not necessary:
x=torch.empty(1)
y=torch.empty(3,1,7)
print((x+y).size())



torch.Size([3, 1, 7])


### Question: The following command does not work. Why?



In [ ]:
x=torch.empty(5,2,4,1)
y=torch.empty(  3,1,1)
print((x+y).size())


In [ ]:
x=2*torch.ones(  2,4)
y=torch.ones(3,2,4)
print(x+y)

### Question: What is the diffence between "x = xr" and "x = xr.clone()"?

In [ ]:
x = xr.clone()
x.add_(-xr)
print(x)
print(xr)

Also be careful, changing the torch tensor modify the numpy array and vice-versa...

In [ ]:
y=torch.ones(2,4)
print(y)
z = y.numpy()
print(z)

In [ ]:
np.add(z, 1, out=z)
print("z=", z)
print("y=", y,"\n")
torch.add(y, -4, out=y)
print("z=",z)
print("y=",y)

## Computational graphs

In [ ]:
import matplotlib.pyplot as plt
%matplotlib inline
import torch

In [ ]:
# Install torchviz if not installed before on your laptop
# !pip install torchviz

# WARNING: You should install the graphviz package in your system (not just the python package).
# If so, you must visit
# https://graphviz.org/download/

In [ ]:
import torchviz

ModuleNotFoundError: No module named 'torchviz'

### Question: Give an interpretation of the information in the graph drawn in the next cell.

In [ ]:
x = torch.ones(2, 2, requires_grad=True)
w = torch.rand(1, 1, requires_grad=True)
print(x)
print(w)
y = w * x + 2
print(y)
torchviz.make_dot(y)

## Create your first neural network (with random parameters)

In [ ]:
import torch
import torch.nn as nn
import torch.nn.functional as F

Let's define the neural network model as a class

In [ ]:
class Net(nn.Module):
    def __init__(self):
      super(Net, self).__init__()
      self.fc1 = nn.Linear(20, 10)
      self.fc2 = nn.Linear(10, 4)

    # x represents our input data
    def forward(self, x):
      # Pass data through fc1
      x = self.fc1(x)
      x = F.relu(x)
      x = self.fc2(x)

      # Apply softmax to x
      output = F.softmax(x, dim=1)
      return output

Let’s instantiate the neural network model

In [ ]:
my_nn = Net()

### Question: test the model by passing some random data through it (3 random vectors following a normal distribution)

Hint: you can look at https://pytorch.org/tutorials/recipes/recipes/defining_a_neural_network.html

In [ ]:
# Code here

### Question: print the computational graph of the neural network with the names of the parameters.

In [ ]:
# Code here

### Question: Verify the sum of each output. How to interpret the output?

In [ ]:
# Code here